-- Farket: şehir referans verisi (Türkiye'nin 81 ili)
--
-- `cities` tablosu boş şekilde deploy edilmişti — `supabase/seed.sql` yalnızca
-- yerelde çalışır ve hiç şehir eklemiyordu, bu yüzden hem yerel geliştirmede
-- hem production'da `set_city`/keşif akışı seçilecek hiçbir şehir bulamıyordu.
-- Bu gerçek prodüksiyon referans verisi olduğu için (soru/taksonomi seed'i gibi)
-- migration olarak ekleniyor, seed.sql'e değil.

insert into public.cities (name, is_active) values
  ('Adana', true),
  ('Adıyaman', true),
  ('Afyonkarahisar', true),
  ('Ağrı', true),
  ('Amasya', true),
  ('Ankara', true),
  ('Antalya', true),
  ('Artvin', true),
  ('Aydın', true),
  ('Balıkesir', true),
  ('Bilecik', true),
  ('Bingöl', true),
  ('Bitlis', true),
  ('Bolu', true),
  ('Burdur', true),
  ('Bursa', true),
  ('Çanakkale', true),
  ('Çankırı', true),
  ('Çorum', true),
  ('Denizli', true),
  ('Diyarbakır', true),
  ('Edirne', true),
  ('Elazığ', true),
  ('Erzincan', true),
  ('Erzurum', true),
  ('Eskişehir', true),
  ('Gaziantep', true),
  ('Giresun', true),
  ('Gümüşhane', true),
  ('Hakkari', true),
  ('Hatay', true),
  ('Isparta', true),
  ('Mersin', true),
  ('İstanbul', true),
  ('İzmir', true),
  ('Kars', true),
  ('Kastamonu', true),
  ('Kayseri', true),
  ('Kırklareli', true),
  ('Kırşehir', true),
  ('Kocaeli', true),
  ('Konya', true),
  ('Kütahya', true),
  ('Malatya', true),
  ('Manisa', true),
  ('Kahramanmaraş', true),
  ('Mardin', true),
  ('Muğla', true),
  ('Muş', true),
  ('Nevşehir', true),
  ('Niğde', true),
  ('Ordu', true),
  ('Rize', true),
  ('Sakarya', true),
  ('Samsun', true),
  ('Siirt', true),
  ('Sinop', true),
  ('Sivas', true),
  ('Tekirdağ', true),
  ('Tokat', true),
  ('Trabzon', true),
  ('Tunceli', true),
  ('Şanlıurfa', true),
  ('Uşak', true),
  ('Van', true),
  ('Yozgat', true),
  ('Zonguldak', true),
  ('Aksaray', true),
  ('Bayburt', true),
  ('Karaman', true),
  ('Kırıkkale', true),
  ('Batman', true),
  ('Şırnak', true),
  ('Bartın', true),
  ('Ardahan', true),
  ('Iğdır', true),
  ('Yalova', true),
  ('Karabük', true),
  ('Kilis', true),
  ('Osmaniye', true),
  ('Düzce', true)
on conflict (name) do nothing;
